### PR TITLE
[ISSUE-218] fix: Change user from None to Anonymous User in authenticated requests

### PR DESCRIPTION
**Pull request by OlhaShyliaieva**
## Description
Modified the `Lti1p3ApiAuthentication` authentication backend. Set up in request `AnonymousUser` instead of `None`.
It allows `DarkLangMiddleware` to work properly without crashing when middleware tries to get a user from the request.

## Supporting information
Issue: https://github.com/openedx/xblock-lti-consumer/issues/218

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @OlhaShyliaieva! I've created [OSPR-6428](https://openedx.atlassian.net/browse/OSPR-6428) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Comment by regisb** [comment]
@giovannicimolin do you have an idea why you (or edX) did not face this issue before? Unless I'm mistaken it should occur for every LTI 1.3 unit, right?

**Comment by giovannicimolin** [comment]
@regisb 
>do you have an idea why you (or edX) did not face this issue before? Unless I'm mistaken it should occur for every LTI 1.3 unit, right?

No idea, I even tried reproducing it on my devstack without success. I worked for me during the implementation phase as well as for @nedbat when he ran the IMS certification tool. 

----

@OlhaShyliaieva Thanks for the contribution! Can you sign the contributor agreement and ping me once it's done? Only then I'll be able to review + move this forward. :grin:

**Comment by e0d** [comment]
@OlhaShyliaieva we've processed an individual CLA for you, but I believe this should be covered under the RaccoonGang Entity CLA. @idegtiarov can you confirm?

**Comment by natabene** [comment]
@OlhaShyliaieva Thank you for your contribution.

**Comment by idegtiarov** [comment]
Hi @e0d I confirm @OlhaShyliaieva is covered with the RaccoonGang Entity CLA.

**Comment by giovannicimolin** [comment]
@natabene CLA check is green now. :smile: 

@OlhaShyliaieva Can you add in a minor version bump ([here](https://github.com/openedx/xblock-lti-consumer/blob/master/lti_consumer/__init__.py#L7)) and add a [changelog](https://github.com/openedx/xblock-lti-consumer#changelog) entry?

**Comment by OlhaShyliaieva** [comment]
@giovannicimolin Done

**Comment by natabene** [comment]
I still see a conflict.

**Comment by giovannicimolin** [comment]
@OlhaShyliaieva I just tested the change and it's working perfectly. A few changes were merged in while this was in my backlog, so can you update the version bump and changelog? Once you do it I'll approve the PR and merge the changes.

**Comment by ormsbee** [comment]
I merged this change in a different PR: https://github.com/openedx/xblock-lti-consumer/pull/261

**Comment by openedx-webhooks** [comment]
@OlhaShyliaieva Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-lti-consumer&entry.867055334=https://github.com/openedx/xblock-lti-consumer/pull/228&entry.1484655318=https://github.com/OlhaShyliaieva&entry.752974735=2022-02-01+10:19&entry.1917517419=2022-07-05+17:51&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
