### PR TITLE
237 lti 1p3 launch permission templates not rendered

### LINKED ISSUE #237: LTI 1p3 launch error/permission templates not rendered
The [lti_1p3_launch_error.html](https://github.com/openedx/xblock-lti-consumer/blob/3.4.3/lti_consumer/templates/html/lti_1p3_launch_error.html) and [lti_1p3_permission_error.html](https://github.com/openedx/xblock-lti-consumer/blob/3.4.3/lti_consumer/templates/html/lti_1p3_permission_error.html) templates are django templates being rendered by `loader.render_mako_template` ([here](https://github.com/openedx/xblock-lti-consumer/blob/3.4.3/lti_consumer/lti_xblock.py#L1168-L1177)).

This results in them being rendered as raw text instead of any variable substitution being done. They are properly rendered when `loader.render_django_template` is used.

### PR DESCRIPTION
**Pull request by geoff-va**
Fixes #237 

- Changes `render_mako_template` -> `render_django_template` in `lti_1p3_launch_callback` exception handlers
- Check that `% trans` is not in response bodies so we know template was properly rendered

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @geoff-va! I've created [OSPR-6504](https://openedx.atlassian.net/browse/OSPR-6504) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Comment by giovannicimolin** [comment]
Thanks for the contribution @geoff-va!
Let me know as soon as you have sorted out the CLA, I can review and merge your PR. :grin:

**Comment by natabene** [comment]
@geoff-va Thank you for the contribution! Once you have signed our Contributor Agreement and it has been processed, you will receive a confirmation via email from our Legal team. We then will be able to review this and all your future code contributions.

**Comment by giovannicimolin** [comment]
@natabene @geoff-va Let me know when the CLA is sorted out :)

**Comment by natabene** [comment]
@geoff-va Thanks for letting us know. Please ping here once you have signed the agreement.

**Comment by geoff-va** [comment]
Ok @natabene the entity CLA has been signed and I should be added! Let me know if you have any questions, thanks!

**Comment by edx-webhook** [comment]
@geoff-va Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-lti-consumer&entry.867055334=https://github.com/openedx/xblock-lti-consumer/pull/238&entry.1484655318=https://github.com/geoff-va&entry.752974735=2022-03-04+20:35&entry.1917517419=2022-03-30+19:12&entry.2133058324=No) so we can improve your experience in the future.

**Comment by natabene** [comment]
@giovannicimolin We are good here, CLA check is green.

**Review by giovannicimolin — CHANGES_REQUESTED** [review]
@geoff-va Code looks good! 

Just a minor thing: Can you add a [version bump](https://github.com/openedx/xblock-lti-consumer/blob/master/lti_consumer/__init__.py#L7) and [a changelog entry](https://github.com/openedx/xblock-lti-consumer/blob/master/README.rst#changelog)?

**Comment by natabene** [comment]
@giovannicimolin Owning team is fine with you reviewing and merging, if you are up to it.

**Comment by geoff-va** [comment]
@giovannicimolin 

* Merged in master since it looks to have been updated since I started
* Bumped version to 3.4.6
* Added ChangeLog entry

**Comment by giovannicimolin** [comment]
@natabene I'll fix the commit lint failure with GitHub's `Squash and merge`.

**Comment by edx-webhook** [comment]
@geoff-va 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-lti-consumer&entry.867055334=https://github.com/openedx/xblock-lti-consumer/pull/238&entry.1484655318=https://github.com/geoff-va&entry.752974735=2022-03-04+20:35&entry.1917517419=2022-03-31+20:03&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
