### PR TITLE
change to new edx user service

### PR DESCRIPTION
**Pull request by sroertgen**
As discussed in #217 edX changed its internal user service.

This PR implements these changes.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @sroertgen! I've created [OSPR-6413](https://openedx.atlassian.net/browse/OSPR-6413) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Comment by giovannicimolin** [comment]
@sroertgen Awesome work here. 
Before we can accept code, we need a signed contributor agreement. Can you follow the instructions above?

Let me know if you have any questions. I'll find the right person to help you if you bump into any issues.

**Comment by natabene** [comment]
@sroertgen 
Thank you for the contribution! Once you have signed our Contributor Agreement and it has been processed, you will receive a confirmation via email from our Legal team. We then will be able to review this and all your future code contributions.

**Comment by sroertgen** [comment]
Thank you both!
I filled out the document and send it to your legal team.

Have a nice weekend!

**Comment by natabene** [comment]
@sroertgen Thank you very much! Once they process it and you are cleared, I will post here.

**Comment by giovannicimolin** [comment]
@sroertgen Some tests are failing because of the User service mock isn't returning proper values, can you fix that? See https://github.com/openedx/xblock-lti-consumer/runs/4982515609?check_suite_focus=true.

**Comment by sroertgen** [comment]
@giovannicimolin oh yes, there are tests :D

I will have a look into this! And thanks for the hints!

**Comment by natabene** [comment]
@sroertgen Thank you for signing, you are all set now. Next commit or rebase should clear the cla check.

**Comment by sroertgen** [comment]
Hey @giovannicimolin,

I fixed the tests. Had a bit of struggle squashing my commits, but I hope it is now as you expect (was a good opportunity for me starting with this best practice ;) )

Please let me know, if I have to do anything else.

**Comment by sroertgen** [comment]
just saw the failing test. I just ran `make test`, but there seem to be more tests as it seems 😃
Will have a look into it

**Comment by giovannicimolin** [comment]
@sroertgen There's quality checks too, make sure you run those as well. :)

**Comment by sroertgen** [comment]
@giovannicimolin If you don't mind, you can try running the workflows again.

**Comment by giovannicimolin** [comment]
@sroertgen Tests running :grin:

**Comment by natabene** [comment]
@sroertgen @giovannicimolin Is this good for our review?

**Review by giovannicimolin — CHANGES_REQUESTED** [review]
@sroertgen Did a full review and testing of the changes and left a few suggestions in the PR.

**Comment by sroertgen** [comment]
Thanks! Will have a look into this during this week!

**Comment by sroertgen** [comment]
Hey @giovannicimolin,

sorry it took a bit longer, but I had to hand in two proposals in the last weeks and just did not have time to work on your suggestions. 

Thanks for the hints! I implemented the changes and am looking forward for your feedback.

Best,
Steffen

**Comment by sroertgen** [comment]
Sorry, my `make quality` test suggested to delete the line that now threw the error. I just put it back in.

**Comment by natabene** [comment]
@giovannicimolin Could you finalize reviewing and merge when ready? Owning team is fine with you review and mege.

**Comment by giovannicimolin** [comment]
@natabene Sure! I'm planning to review this today - sorry for the delay in the reply.

**Comment by natabene** [comment]
@giovannicimolin Thanks!

**Review by giovannicimolin — APPROVED** [review]
:+1:

- [x] I tested this:
1. Tested LTI 1.1 launches from both the LMS and Studio and checked the data.
2. Individually tested each method modified and checked it's results on the LMS and Studio environments using a debugger. 
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ NA
- [ ] ~~Includes documentation~~ NA

@sroertgen Great work! Thanks for the contribution.

I'll fix the commit-lint error using GitHub's squash and merge feature.

**Comment by edx-webhook** [comment]
@sroertgen 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-lti-consumer&entry.867055334=https://github.com/openedx/xblock-lti-consumer/pull/224&entry.1484655318=https://github.com/sroertgen&entry.752974735=2022-01-25+15:15&entry.1917517419=2022-03-18+20:38&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
