### PR TITLE
refactor: replace usages of get_real_user and course_id [BD-13]

### PR DESCRIPTION
**Pull request by xitij2000**
Replaces usages of `get_real_user` with the `UserService` and `course_id` with `runtime.scope_ids.usage_id.context_key`

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @xitij2000!


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by giovannicimolin** [comment]
@xitij2000 I can review this one, can you rebase and fix the conflicts? I can review and test.
Also, is there any risk for the discussions LTI integrations with this change?

**Comment by Agrendalath** [comment]
Closing, as we included this in https://github.com/openedx/xblock-lti-consumer/pull/249.

**Comment by openedx-webhooks** [comment]
@xitij2000 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-lti-consumer&entry.867055334=https://github.com/openedx/xblock-lti-consumer/pull/291&entry.1484655318=https://github.com/xitij2000&entry.752974735=2022-10-05+11:20&entry.1917517419=2022-11-22+14:00&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
