### PR TITLE
fix: Fix quote rendering on LTI 1.1 form

### LINKED ISSUE #177: Course title is truncated when there's `"` in the title on LTI 1.1 launches
When launching an LTI 1.1 problem from a course that contains the `"` character in the title, the title gets truncated in the LTI form, and the message signature verification fails. 
This is probably an escaping issue when rendering the form.

### PR DESCRIPTION
**Pull request by giovannicimolin**
This PR:
* Fixes quotes being rendered on LTI 1.1 launch templates by switching to Django template (from Mako template) - they handle escaping characters better.
* Internationalize strings on LTI 1.1 launch page.

Fixes #177.

_This also helps us get rid of the Mako templates._ :grin:

**Testing instructions:**
1. **Use the master branch.**
2. Set up a LTI passport on a course's advanced settings (I'm using the saLTIre test tool - https://saltire.lti.app/tool, no setup required there):
```
[
    "test:jisc.ac.uk:secret"
]
```
3. Add `lti_consumer` to the advanced module list.
4. Create a new section, subsection and unit and add a LTI Consumer block.
5. Set these options:
```
Display name: LTI Consumer "        <- Don't forget the double quote at the end
LTI ID: test
LTI URL: https://saltire.lti.app/tool
```
6. Save and check the output.
image
_Optionally inspect the parameters: you'll see the missing quote in the name._
7. **Switch to this branch and refresh the page.**
8. Profit.
image

**Reviewers:**
- [ ] @Agrendalath 
- [x] @schenedx

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @giovannicimolin! I've created [OSPR-6429](https://openedx.atlassian.net/browse/OSPR-6429) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by schenedx — APPROVED** [review]
👍  LGTM. Are there any other templates we should convert from mako to django? Is this the only one in this repository?

**Comment by giovannicimolin** [comment]
@schenedx There's still a few Mako templates lying around:

1. https://github.com/openedx/xblock-lti-consumer/blob/master/lti_consumer/templates/html/student.html (this is the most complex, can and should be simplified if possible).
2. https://github.com/openedx/xblock-lti-consumer/blob/master/lti_consumer/templates/html/lti_iframe.html ([imported from `student.html`](https://github.com/openedx/xblock-lti-consumer/blob/master/lti_consumer/templates/html/student.html#L66) - converting it is not that easy because of template path issues)
3. https://github.com/openedx/xblock-lti-consumer/blob/master/lti_consumer/templates/html/lti_1p3_launch.html (easy port - almost the same as the current PR)

I plan to tackle them in the next few sprints as part of my CC duties, but these are not  high priority tasks.

**Comment by edx-webhook** [comment]
@giovannicimolin 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-lti-consumer&entry.867055334=https://github.com/openedx/xblock-lti-consumer/pull/230&entry.1484655318=https://github.com/giovannicimolin&entry.752974735=2022-02-01+20:40&entry.1917517419=2022-02-02+15:15&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by giovannicimolin** [comment]
Merged & released!

**Comment by natabene** [comment]
@giovannicimolin @schenedx Thank you both!

**Pull request merged**
