### PR TITLE
fix: CCX LTI configuration compatibility

### PR DESCRIPTION
**Pull request by kuipumu**
## Description

This PR adds compatibility fix for CCXs and external reusable configurations to the LTI consumer XBlock. This also includes changes to previously added fixes for CCXs using the LTI consumer XBlock. This changes allow the LTI consumer XBlock to sync values from the main CCX LTI configuration model to all of it's children CCX LTI configurations and vice versa.

## Type of Change

- [x] Remove previous CCX fixes.
- [x] Add model_to_dict function to utils module.
- [x] Add LtiConfiguration sync_configurations method.
- [x] Modify LtiConfiguration save method.
- [x] Include tests for all added and modified code.

## Testing

1. Create a course and add a LTI consumer XBlock.
2. Create a CCX of the previously created course. 
3. Launch the CCX course unit with the LTI consumer XBlock.
4. Go to http://localhost:18000/admin/lti_consumer/lticonfiguration/.
5. Both the main LTI configuration and it's children CCX configuration should have the same values.
6. Update any value on the main LTI configuration.
7. Go to the children CCX LTI configuration.
8. The values from the main LTI configuration should be reflected.
9. Delete both LTI configurations.
10. Launch the CCX course unit with the LTI consumer XBlock.
11. Launch the course unit with the main LTI consumer XBlock.
12. Go back to the LTI configuration admin and search for both newly created configurations.
13. Both LTI configurations values should be synced.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @kuipumu!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @kuipumu! Is this ready for review/merge? Thanks!

**Comment by kuipumu** [comment]
@mphilbrick211 Yes, this is ready for review/merge

**Comment by mphilbrick211** [comment]
Hi @chennighan2u and @openedx/masters-devs-cosmonauts! Could someone please review and merge this for us? Thanks!

**Comment by mphilbrick211** [comment]
Hi @kuipumu! Some branch conflicts have popped up while waiting for review - would you mind taking a look?

**Comment by kuipumu** [comment]
Hi @mphilbrick211, just added a commit to resolve the branch conflicts

**Review by Zacharis278 — COMMENTED** [review]
This looks good to me 👍 

@kuipumu before we merge can you add a changelog entry and update __init__.py with the new version?

**Comment by kuipumu** [comment]
@Zacharis278 Great!, I just added a commit to bump the version an update the changelog

**Comment by mphilbrick211** [comment]
Hi @kuipumu! Looks like some branch conflicts have popped up. Would you mind taking a look? Thanks!

**Comment by kuipumu** [comment]
Hi @mphilbrick211, I pushed a commit to resolve the conflicts

**Review by Zacharis278 — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@kuipumu 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-lti-consumer&entry.867055334=https://github.com/openedx/xblock-lti-consumer/pull/391&entry.1484655318=https://github.com/kuipumu&entry.752974735=2023-07-10+22:35&entry.1917517419=2023-08-21+14:18&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
