### PR TITLE
docs: fix translations update instructions

### LINKED ISSUE #354: Not all languages have been included in the release
There are multiple languages that have not been updated, probably because the "Downloading translations from Transifex" instructions don't include them.

### PR DESCRIPTION
**Pull request by igobranco**
closes #354

Removes from the README.md the incorrect instructions to update only some languages instead of all.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @igobranco!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by Zacharis278 — APPROVED** [review]
Agreed, there's no reason to limit this.

**Comment by mphilbrick211** [comment]
@chennighan2u - another one for your review/merge!

**Review by felipemontoya — APPROVED** [review]
This is only modifying the readme. Also there is agreement that we should not be hardcoding a limited list of languages.

@chennighan2u would you also agree this can be merged?

**Review by chennighan2u — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@igobranco 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-lti-consumer&entry.867055334=https://github.com/openedx/xblock-lti-consumer/pull/355&entry.1484655318=https://github.com/igobranco&entry.752974735=2023-04-12+15:31&entry.1917517419=2023-05-11+21:41&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
