### PR TITLE
Fix github url strings (org edx -> openedx)

### PR DESCRIPTION
**Pull request by sarina**
## This PR was autogenerated

This pr replaces the old GitHub organization, github.com/edx, with the new GitHub organization, github.com/openedx.

Tagging @openedx/tcril-engineering for review, but others are welcome to provide review.

Ref: https://github.com/openedx/tcril-engineering/issues/42

### CODE REVIEW

**Comment by mphilbrick211** [comment]
Hi @giovannicimolin! Could you please review now that it has been rebased? Thank you!

**Comment by sarina** [comment]
Hey Michelle, this doesn't need Giovanni's review. He has asked me to do
something and I haven't done it yet. I did not rebase this branch.

**Comment by mphilbrick211** [comment]
> 

Sorry about that!

**Comment by sarina** [comment]
@giovannicimolin thanks for the feedback - my script did miss things and I'm impressed you caught them! 😁 

I put response to your feedback in a separate commit. If this gets your 👍🏻 feel free to squash and merge (or I can!)

**Comment by giovannicimolin** [comment]
@sarina Thanks! I'll review and merge it tomorrow :)

**Review by giovannicimolin — APPROVED** [review]
:+1: 

All the links are updated now!

- [ ] ~~I tested this~~ NA
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ NA
- [x] Includes documentation

@sarina Good to go! :grin:

**Pull request merged**
