### PR TITLE
chore: update translations

### PR DESCRIPTION
**Pull request by igobranco**
Update the missing translations of ja_JP and pt_PT languages.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @igobranco!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @igobranco! Would you mind taking a look at resolving the branch conflicts?

Also, friendly ping for review @chennighan2u. Thanks!

**Comment by felipemontoya** [comment]
I tested this locally and it worked as expected. @igobranco could you please give me access to your fork so I can update the PR?

**Comment by igobranco** [comment]
Hi @mphilbrick211 and @felipemontoya,
I've resolved the merge conflits. The origin of the merge conflict was because of the "[standardize translation directory for i18n_tool](https://github.com/openedx/xblock-lti-consumer/commit/e4bb599fea663f8c573dfce26e8f26bb082b6810)".
It seems that the translations of the fa_CA was updated, so I've updated the PR to include only the pt_PT and ja_JP.

**Review by felipemontoya — APPROVED** [review]
With the update this is good to be merged!
Thanks @igobranco

**Comment by mphilbrick211** [comment]
> @chennighan2u I forgot to tag you as well, but we'd like your opinion here. As a reviewer I tested this and its ready to merge. The changes are only additive and the affect two languages that have not been pulled by the transifex bot in a long time.

Hi @chennighan2u @openedx/enterprise-titans - just flagging this request for you. Thanks!

**Comment by chennighan2u** [comment]
@mphilbrick211 do we also need the text.js files to also update for this?

**Comment by mphilbrick211** [comment]
> @mphilbrick211 do we also need the text.js files to also update for this? Or, is this unnecessary for the first part of this and we don't need implementation yet?

Hi @chennighan2u - I'm actually not sure, so I'm hoping @felipemontoya or @igobranco can shed some light on that for you.

**Comment by mphilbrick211** [comment]
Hi @chennighan2u - are you able to merge this if all looks good? Thanks!

**Comment by mphilbrick211** [comment]
> Hi @chennighan2u - are you able to merge this if all looks good? Thanks!

cc: @openedx/masters-devs-cosmonauts

**Comment by openedx-webhooks** [comment]
@igobranco 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-lti-consumer&entry.867055334=https://github.com/openedx/xblock-lti-consumer/pull/356&entry.1484655318=https://github.com/igobranco&entry.752974735=2023-04-12+15:38&entry.1917517419=2023-06-20+20:11&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
