### PR TITLE
FAL-2844: Fix LTI Deep Linking permissions issues

### PR DESCRIPTION
**Pull request by giovannicimolin**
This PR fixes a permissions check issue when saving Deep Linking content edits back into Studio. This was caused by the incorrect API being used causing it to error out when any user other than a superuser was used.

We're basically replacing the old check with a new call to Studio's `has_studio_write_access` with the right parameters.

**Testing instructions:**
_Testing instructions written to members with access to H5P testing tools._

Before following these instructions, make sure you have a publicly accessible devstack set up (instructions [here](https://github.com/openedx/xblock-lti-consumer#lti-13) - ignore the LTI tool setup steps).

1. Set up a LTI 1.3 integration on H5P (from H5P dashboard: `Manage organization` -> `Connect LMS`).
2. Add a new LTI consumer block in your devstack and configure it to use the H5P tool. Leave this tab open.
3. Change `lms.yml` variables to enable secure cookies with `SameSite=None` and restart the LMS:
```
LMS_ROOT_URL: yourtunnelurl.domain.com
SESSION_COOKIE_SECURE: true
DCS_SESSION_COOKIE_SAMESITE: None
```
_After this step, only logins from your secure `https` URL will work._
4. Go back to the studio tab and click on the `Deep Linking Launch - Configure tool` link.
5. Author a new problem and click `Save and insert` in H5P.
6. Wait for the LMS message mentioning that the content was saved.
7. Refresh the Studio page and check that the content you selected in H5P is listed there.
image
8. Launch the content from the LMS.

**Validation testing (edX only):**
Not required, but useful to confirm the changes are working as expected. 

**Reviewers:**
- [ ] @Agrendalath 
- [ ] @schenedx

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @giovannicimolin! I've created [OSPR-6527](https://openedx.atlassian.net/browse/OSPR-6527) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Review by schenedx — APPROVED** [review]
I verified that `has_studio_write_access` is like a wrapper around LMS `has_access` function which both the old code `user_has_access` uses.
So this change is definitely good.
👍

**Comment by natabene** [comment]
@giovannicimolin Thank you for your contribution, and @schenedx Thanks for your review. Would you like to merge it?

**Comment by schenedx** [comment]
@natabene I'll let @giovannicimolin clean this up and merge. I can help Giovanni to merge the edx-platform version bump PR tho

**Comment by edx-webhook** [comment]
@giovannicimolin 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-lti-consumer&entry.867055334=https://github.com/openedx/xblock-lti-consumer/pull/240&entry.1484655318=https://github.com/giovannicimolin&entry.752974735=2022-03-16+17:14&entry.1917517419=2022-03-21+14:03&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
