### PR TITLE
[WIP] feat: Develop customization to allow administrators set LTI keys centrally. [BB-4974]

### PR DESCRIPTION
**Pull request by Cup0fCoffee**

### CODE REVIEW

**Comment by natabene** [comment]
@Cup0fCoffee Just checking if you are still interested in pursuing this PR.

**Comment by Cup0fCoffee** [comment]
@natabene Yes, we (Opencraft) have been planing to work on this, but have been pushing it back. I can close the PR, and open a new one once we decide to complete the implementation.

**Comment by natabene** [comment]
@Cup0fCoffee Sounds good, thanks for an update. I will close, please re-open or open a new one once ready for our review.

**Comment by edx-webhook** [comment]
@Cup0fCoffee Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-lti-consumer&entry.867055334=https://github.com/openedx/xblock-lti-consumer/pull/201&entry.1484655318=https://github.com/Cup0fCoffee&entry.752974735=2021-10-15+14:23&entry.1917517419=2022-01-12+14:54&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
