### PR TITLE
fix: Missing external configuration error message

### PR DESCRIPTION
**Pull request by kuipumu**
## Description

This PR adds a fix for the LTI external configurations feature issue https://github.com/openedx/xblock-lti-consumer/issues/420

## Type of Change

- [x] Modify `_get_lti_config_for_block` function on `plugin/api.py` module to raise an `ExternalConfigurationNotFound` error when no external LTI configuration is found.

## Testing

1. Create a course and add a LTI consumer XBlock.
2. Edit the XBlock settings and set "Configuration Type" to "Reusable Configuration".
3. Edit the XBlock settings and set "LTI Reusable Configuration ID" to an nonexistent external configuration (Ex: test:test).
4. Save the XBlock and reload the studio editor.
5. The studio view should show an exception.
6. Go to the learning MFE and load the unit where the XBlock is.
7. The learning MFE should show an general unexpected exception.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @kuipumu!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @kuipumu! Would you mind rebasing this pull request? Doing so might help resolve the codecov errors. If that doesn't work, I'll look into it for you. Thanks!

**Comment by mphilbrick211** [comment]
> Hi @kuipumu! Would you mind rebasing this pull request? Doing so might help resolve the codecov errors. If that doesn't work, I'll look into it for you. Thanks!

Hi @kiram15! Friendly follow-up on this!

**Comment by mphilbrick211** [comment]
Hi @kuipumu! Just checking in to see if you plan to pursue this pull request?

**Comment by mphilbrick211** [comment]
Hi @kuipumu! I'm going to close this pull request for now, but we can reopen in the future if you'd like to pursue. Thanks!

**Comment by openedx-webhooks** [comment]
@kuipumu Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-lti-consumer&entry.867055334=https://github.com/openedx/xblock-lti-consumer/pull/423&entry.1484655318=https://github.com/kuipumu&entry.752974735=2023-10-25+23:11&entry.1917517419=2024-03-20+01:27&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
